import { ReactNode } from "react";
import { Sen } from "next/font/google";

import "./reset.scss";
import "./global.scss";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import { Footer, Header } from "components";

const sen = Sen({ subsets: ["latin"] });

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={sen.className}>
        <NextIntlClientProvider messages={messages}>
          <Header />
          <main>{children}</main>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
